default:
  image: python:3.8.2-alpine3.11
  tags:
    - shared-exec-docker

variables:
  SITE_BUNDLE: agargiulo-com.tar

stages:
  - build
  - deploy
  - trigger

tar:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apk add tar &> /dev/null
  script:
    - tar -C ../ -cf "${SITE_BUNDLE}" --exclude-vcs --exclude "${SITE_BUNDLE}" "${CI_PROJECT_NAME}"
  artifacts:
    paths:
      - "${SITE_BUNDLE}"
    expire_in: 1 hour

deploy3:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - python3 -m pip install awscli &> /dev/null
  script:
    - aws s3 cp "${SITE_BUNDLE}" "s3://${AGARG_php_s3}/${CI_COMMIT_REF_NAME}/${CI_COMMIT_SHORT_SHA}-${SITE_BUNDLE}"

trigger-www_agarg_ami:
  stage: trigger
  variables:
    AGARGIULO_COM_PHP_VERSION: ${CI_COMMIT_REF_NAME}
  trigger:
    project: agargiulo/www_agarg_ami
    branch: multi-pipeline
    strategy: depend
